### ISSUE TITLE
Failed to parse SRCINFO: invalid version string

### ISSUE THREAD

**Issue by AladW** [simon04/aur-out-of-date#10]
```
[archie@v22018013960760236 sync]$ aur out-of-date -devel -local */.SRCINFO
panic: Failed to parse shaman-git/.SRCINFO: invalid version string: 2.0.0.α.r29.g18fc492

goroutine 1 [running]:
main.handlePackages(0xc420011500, 0x0, 0x0, 0x0, 0x71b6c0, 0xc4202b0500)
        /home/archie/.cache/aurutils/snapshot/aur-out-of-date/src/_go/src/github.com/simon04/aur-out-of-date/main.go:82 +0x301
main.main()
        /home/archie/.cache/aurutils/snapshot/aur-out-of-date/src/_go/src/github.com/simon04/aur-out-of-date/main.go:127 +0x42d
```
The .SRCINFO file in question:
```
# Generated by mksrcinfo v8
# Wed Jan 13 23:31:41 UTC 2016
pkgbase = shaman-git
        pkgdesc = A small, native C library and utility to fetch weather
        pkgver = 2.0.0.α.r29.g18fc492
        pkgrel = 1
        url = https://github.com/HalosGhost/shaman
        arch = i686
        arch = x86_64
        license = GPL2
        makedepends = git
        makedepends = tup
        makedepends = clang
        makedepends = python-sphinx
        depends = curl
        depends = jansson
        source = git+https://github.com/HalosGhost/shaman.git
        sha256sums = SKIP

pkgname = shaman-git
```
By PKGBUILD(5), such characters are allowed in `pkgver`.  Compare https://bugs.archlinux.org/task/49342

**Comment by AladW** [comment]
Sorry, I forgot I already filed #7.
