### ISSUE TITLE
AUR package fails to build because of error in check()

### ISSUE THREAD

**Issue by goggle** [simon04/aur-out-of-date#26]
I'm trying to install this from the AUR, I always get that error:
```
==> Making package: aur-out-of-date 1.5.0-1 (So 16 Sep 2018 15:08:17 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found aur-out-of-date-1.5.0.tar.gz
==> Validating source files with sha256sums...
    aur-out-of-date-1.5.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting aur-out-of-date-1.5.0.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
==> Starting check()...
?   	github.com/simon04/aur-out-of-date	[no test files]
ok  	github.com/simon04/aur-out-of-date/config	(cached)
--- FAIL: TestSplitPkg (0.33s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 5 [running]:
testing.tRunner.func1(0xc0000fc100)
	/usr/lib/go/src/testing/testing.go:792 +0x387
panic(0x6aa220, 0x917180)
	/usr/lib/go/src/runtime/panic.go:513 +0x1b9
github.com/simon04/aur-out-of-date/pkg.TestSplitPkg(0xc0000fc100)
	/home/alex/builds/aur-out-of-date/src/_go/src/github.com/simon04/aur-out-of-date/pkg/local_test.go:16 +0x2b9
testing.tRunner(0xc0000fc100, 0x7109f8)
	/usr/lib/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:878 +0x353
FAIL	github.com/simon04/aur-out-of-date/pkg	0.337s
ok  	github.com/simon04/aur-out-of-date/rfc7464	(cached)
ok  	github.com/simon04/aur-out-of-date/status	(cached)
ok  	github.com/simon04/aur-out-of-date/upstream	(cached)
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by simon04** [comment]
Fixed in https://github.com/simon04/aur-out-of-date/commit/abe1d18f516c9fec0a24db9fa4bbce5dcda09098 and published a new version. Thanks for reporting!
