### ISSUE TITLE
debian: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by simon04** [simon04/aur-out-of-date#32]
```
 goroutine 1 [running]:
github.com/simon04/aur-out-of-date/upstream.debian.latestVersion(0xc0002bc316, 0xa, 0x51, 0xc0002ef800, 0x2, 0x2)
        /home/haawda/paketierung/not_maintained_by_me/aur-out-of-date/src/aur-out-of-date-2.1.0/upstream/debian.go:31 +0x233
github.com/simon04/aur-out-of-date/upstream.forURL(0xc0002bc2ea, 0x51, 0x1, 0x1, 0x0, 0x0)
        /home/haawda/paketierung/not_maintained_by_me/aur-out-of-date/src/aur-out-of-date-2.1.0/upstream/version.go:89 +0xc99
github.com/simon04/aur-out-of-date/upstream.VersionForPkg(0x55742ed4b8a0, 0xc00021a058, 0x5, 0x0, 0x8, 0xc0000b1bf8)
        /home/haawda/paketierung/not_maintained_by_me/aur-out-of-date/src/aur-out-of-date-2.1.0/upstream/version.go:106 +0x183
main.handlePackage(0x55742ed4b8a0, 0xc00021a058, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/haawda/paketierung/not_maintained_by_me/aur-out-of-date/src/aur-out-of-date-2.1.0/main.go:47 +0x171
main.handlePackages(0xc0005c4000, 0xc00023a000, 0x1a0, 0x200, 0x0, 0x0)
        /home/haawda/paketierung/not_maintained_by_me/aur-out-of-date/src/aur-out-of-date-2.1.0/main.go:117 +0x21c
main.main()
        /home/haawda/paketierung/not_maintained_by_me/aur-out-of-date/src/aur-out-of-date-2.1.0/main.go:155 +0x8b0
```

cc: @z3ntu

**Comment by z3ntu** [comment]
What package was this run on?

**Comment by stefanhusmann** [comment]
It was run with no specific package, but with -user option for user haawda.

**Comment by z3ntu** [comment]
It took nearly a minute to run but it runs through fine on my machine.

**Comment by stefanhusmann** [comment]
I now rebuilt the package and cannot reproduce either. Sorry for the noise.

**Comment by z3ntu** [comment]
Maybe it was a temporary problem with the debian.org API...

**Comment by z3ntu** [comment]
Maybe it was a temporary problem with the debian.org API...
